from enum import StrEnum

class DPG_WIDGETS(StrEnum):
    MESH_DRAW_BACKGROUND = "MESH_DRAW_BACKGROUND"
    MESH_DRAW_LAYER = "MESH_DRAW_LAYER"
    MESH_DRAW_AREA = "MESH_DRAW_AREA"
    MODEL_PATH_TEXT = "MODEL_PATH_TEXT"
    MODEL_CHOOSE_DIALOG_BTN = "MODEL_CHOOSE_DIALOG_BTN"
    MODEL_INFO_TEXT = "MODEL_INFO_TEXT"
    EXP_F_PLOT = "EXP_F_PLOT"
    EXP_V_PLOT = "EXP_V_PLOT"
    EXP_DATA_PATH = "EXP_DATA_PATH"
    PLOT_EXP_V_X = "PLOT_EXP_V_X"
    PLOT_EXP_V_Y = "PLOT_EXP_V_Y"
    PLOT_EXP_F_X = "PLOT_EXP_F_X"
    PLOT_EXP_F_Y = "PLOT_EXP_F_Y"
    EXP_V_LINE = "EXP_V_LINE"
    EXP_F_LINE = "EXP_F_LINE"
    SOLVER_PATH = "SOLVER_PATH"
    WORK_DIR = "WORK_DIR"
    MAT_RHO_INPUT = "MAT_RHO_INPUT"
    MAT_E_INPUT = "MAT_E_INPUT"
    MAT_NU_INPUT = "MAT_NU_INPUT"
    MAT_S0_INPUT = "MAT_S0_INPUT"
    MAT_ET_INPUT = "MAT_ET_INPUT"
    NUM_POINTS_INPUT = "NUM_POINTS_INPUT"
    TASK_TYPE = "TASK_TYPE"
    PLOT_DIAG_X = "PLOT_DIAG_X"
    PLOT_DIAG_Y = "PLOT_DIAG_Y"
    PLOT_COMPARE_FORCE_X = "PLOT_COMPARE_FORCE_X"
    PLOT_COMPARE_FORCE_Y = "PLOT_COMPARE_FORCE_Y"
    PLOT_MAXEP_X = "PLOT_MAXEP_X"
    PLOT_MAXEP_Y = "PLOT_MAXEP_Y"
    PLOT_DEP_X = "PLOT_DEP_X"
    PLOT_DEP_Y = "PLOT_DEP_Y"
    PLOT_CONVERGENCE_X = "PLOT_CONVERGENCE_X"
    PLOT_CONVERGENCE_Y = "PLOT_CONVERGENCE_Y"
    LINE_CONVERGENCE = "LINE_CONVERGENCE"
    LINE_DIAG = "LINE_DIAG"
    LINE_COMPARE_FORCE_EXP = "LINE_COMPARE_FORCE_EXP"
    LINE_COMPARE_FORCE_CALC = "LINE_COMPARE_FORCE_CALC"
    LINE_MAXEP = "LINE_MAXEP"
    LINE_DEP = "LINE_DEP"
    ITERATIONS_COUNT_TEXT = "ITERATIONS_COUNT_TEXT"
    ITERATIONS_COUNT_INPUT = "ITERATIONS_COUNT_INPUT"
    RUN_N_ITERATIONS_BTN = "RUN_N_ITERATIONS_BTN"
    NUM_CPUS_INPUT = "NUM_CPUS_INPUT"
    SOLUTION_PROGRESS = "SOLUTION_PROGRESS"
    CONVERGENCE_CRIT_INPUT = "CONVERGENCE_CRIT_INPUT"
    STOP_BUTTON = "STOP_BUTTON"



MESH_DRAW_AREA_WIDTH = 400
MESH_DRAW_AREA_HEIGH = 400

WINDOW_WIDTH=900
WINDOW_HEIGHT=800